FROM tests:latest as firmware
FROM qemu_stm32:latest as emulator

COPY --from=firmware /toolkit/ /toolkit/ 
COPY --from=firmware /app/build/tests_stm32.bin /app/firmware.bin

# files for debugging
COPY --from=firmware /app/ /app/source

ENV PATH="/toolkit/arm-none-eabi/bin:${PATH}"
ENV PATH="/usr/local/bin/qemu_stm32:${PATH}"
ENV PATH="/usr/bin/python3.8:${PATH}"

WORKDIR /test
COPY test_in_docker.sh ./
COPY verify_output.py ./

# with debug. This will not work without gdb connected
#ENTRYPOINT ["qemu-system-arm", "-nographic", "-M", "stm32-f103c8", "-gdb", "tcp::3333", "-S", "-kernel", "/app/firmware.bin", \
#            "-serial", "pty"]

# without debug
# ENTRYPOINT ["qemu-system-arm", "-nographic", "-M", "stm32-f103c8", "-kernel", "/app/firmware.bin", \
#           "-serial", "pty"]

ENTRYPOINT [ "./test_in_docker.sh" ]