FROM tests:latest AS firmware
FROM qemu_stm32:latest AS emulator

COPY --from=firmware /toolkit/ /toolkit/ 
COPY --from=firmware /app/build/test_project.bin /app/firmware.bin
COPY --from=firmware /app/build/test_project.elf /app/firmware.elf

# files for debugging
COPY --from=firmware /app/ /app/source

ENV PATH="/toolkit/arm-none-eabi/bin:${PATH}"
ENV PATH="/usr/local/bin/qemu_stm32:${PATH}"
ENV PATH="/usr/bin/python3.8:${PATH}"

WORKDIR /test
COPY test_in_docker.sh ./
COPY verify_output.py ./

# Set ENTRYPOINT to the script
ENTRYPOINT [ "./test_in_docker.sh" ]
