name: CI

on: 
    push:
    pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run test
      run: cd test && ./test.sh

    - name: Archive test results and logs output
      uses: actions/upload-artifact@v4
      with:
        name: combined_logs
        path: |
          ./test/logs/logs.txt
          ./test/logs/serial_output.txt
